name: hotel_pos
description: "Zero Cost Offline First Hotel POS and Supply System"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  qr_flutter: ^4.1.0

  # डेटाबेस व बैकएंड सिंक
  supabase_flutter: ^2.5.6
  shared_preferences: ^2.2.3
  http: ^1.2.0

  # ब्लूटूथ थर्मल प्रिंटर व पर्ची राइटर्स
  print_bluetooth_thermal: ^1.1.2
  esc_pos_utils_plus: ^2.0.4

  # PDF जनरेशन, स्क्रीनशॉट व शेयरिंग
  pdf: ^3.10.8
  screenshot: ^2.3.0
  path_provider: ^2.1.2
  share_plus: ^9.0.0

  # ऑटो-अपडेट, आवाज (TTS) व तारीख फॉर्मेटिंग
  ota_update: ^5.0.0
  flutter_tts: ^4.0.2
  intl: ^0.19.0

  # नेक्स्ट-लेवल बिज़नेस चार्ट्स व ग्राफिक्स
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/NotoSansDevanagari-Regular.ttf
