name: hotel_pos
description: "Hotel POS System"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.2.2
  supabase_flutter: ^2.8.0
  shared_preferences: ^2.2.2
  print_bluetooth_thermal: ^1.1.2
  esc_pos_utils_plus: ^2.0.3
  screenshot: ^3.0.0
  image: ^4.1.7
  pdf: ^3.10.8
  path_provider: ^2.1.2
  share_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
